### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by eguskov** [eguskov/ecs#1]
- [x] Query
- [x] Codegen
- [x] Delete entity
- [x] Inline system call
- [ ] Threads
- [x] Optimization: Store components of entities in SoA in chunks according to a template. This must improve a performance of queries. For example, now all positions are stored in one array for any of template. So, it must be separated into multiple arrays of positions according to its template. Thus, each array will be containing positions of one template and fast iterating could be done.
- [ ] Optional components Rust-like
- [ ] Replace JSON syntax with Custom using PEGTL for parsing
- [ ] Build templates.json in version without "extends". Do not allow to create entities by templates that are included in another.
This means separation "template" - "template-for-extend"
